import type { Metadata } from 'next'
import './globals.css'

import { GeistMono } from 'geist/font/mono'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={GeistMono.className}>
            <body>{children}</body>
        </html>
    )
}
